### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ulthiel** [ulthiel/HeckeAlgebras.jl#1]
- [ ] Type hierarchy needs some rethinking (especially the general free module with basis stuff)
- [ ] Code needs cleanup
- [ ] Base change should not be via colon operator H:x but via H(x) I think
- [ ] Tests
